export { default as Navbar } from '../components/navbar/Navbar'
export { default as Footer } from '../components/footer/Footer'
export { default as Hero } from '../components/hero/Hero'
export { default as Events } from '../components/events/Events'
export { default as Newrooms } from '../components/newrooms/Newrooms'
export { default as Works } from '../components/howItWork/Works'
export { default as Success } from '../components/success/Success'
export { default as Popularrooms } from '../components/popularrooms/Popularrooms'
export { default as Businesscard } from '../components/businesscard/Businesscard'
export { default as Trustus } from '../components/trustus/Trustus'
export { default as Rent } from '../components/rent/Rent'

